### ISSUE TITLE
Health check

### ISSUE THREAD

**Issue by alxcohen** [pru-mike/rocketchat-jira-webhook#3]
Hi. Will it work with rocketcaht 5+ ?
I got health status like this
{"ok":true,"jira":{"name":"*****","error":""},"confluence":{"name":"","error":"confluence not configured"}}
I'm 100% sure this account is ok, I'm using it for rocketchat jira integration. So what else it could be?
Thanks.

**Comment by pru-mike** [comment]
Hello.
Yeah, it works with Rocket.Chat 5+, just checked it on 5.0.5 and have no any problem.
You should examine  application and rocket logs, and carefully check you configuration.
I have updated the instructions, see [README](https://github.com/pru-mike/rocketchat-jira-webhook/blob/master/README.md), it should helps.

**Comment by alxcohen** [comment]
@pru-mike 
thanks for reply, where in config I can set token ? (rocket couldn't save webhook w\o token ((

"{"ok":true,"jira":{"name":"jirocket","error":""},"confluence":{"name":"","error":"confluence not configured"}}"
ok":true,"jira":{"name":"jirocket","**error**":""},
what does mean this error? login error or connection?

**Comment by pru-mike** [comment]
It's in "rocketchat / token" section,  see in [example](https://github.com/pru-mike/rocketchat-jira-webhook/blob/master/examples/everything.toml)

This error means "no error", it's empty :)
I thought "ok: true" is self explanatory, but maybe it is not

**Comment by alxcohen** [comment]
thanks a lot)

**Comment by alxcohen** [comment]
well. it was permissions issue )
now everything works great!)
thanks !
